# -*- coding: utf-8 -*-
"""mod-4-ipa-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18B2HJiCFdhbKp30ZOVV8yQVT1_JSV432
"""

from IPython.core.display import JSON
'''Module 4: Individual Programming Assignment 1

Parsing Data

This assignment covers your ability to manipulate data in Python.
'''

def relationship_status(from_member, to_member, social_graph):
    '''Relationship Status.
    20 points.

    Let us pretend that you are building a new app.
    Your app supports social media functionality, which means that users can have
    relationships with other users.

    There are two guidelines for describing relationships on this social media app:
    1. Any user can follow any other user.
    2. If two users follow each other, they are considered friends.

    This function describes the relationship that two users have with each other.

    Please see "assignment-4-sample-data.py" for sample data. The social graph
    will adhere to the same pattern.

    Parameters
    ----------
    from_member: str
        the subject member
    to_member: str
        the object member
    social_graph: dict
        the relationship data    

    Returns
    -------
    str
        "follower" if fromMember follows toMember,
        "followed by" if fromMember is followed by toMember,
        "friends" if fromMember and toMember follow each other,
        "no relationship" if neither fromMember nor toMember follow each other.
    '''
    # Replace `pass` with your code. 
    # Stay within the function. Only use the parameters as input. The function should return your answer.
    from_user = social_graph.get(from_member)
    to_user = social_graph.get(to_member)
    from_following_list = from_user.get("following")
    to_following_list = to_user.get("following")
    from_follows_to = to_member in from_following_list
    to_follows_from = from_member in to_following_list
    follow_status = ["friends","follower","followed by","no relationship"]
    if from_follows_to == True and to_follows_from == True:
      return follow_status[0]
    elif from_follows_to == True:
      return follow_status[1]
    elif to_follows_from == True:
      return follow_status[2]
    else:
      return follow_status[3]

def tic_tac_toe(board):
    '''Tic Tac Toe. 
    25 points.

    Tic Tac Toe is a common paper-and-pencil game. 
    Players must attempt to successfully draw a straight line of their symbol across a grid.
    The player that does this first is considered the winner.

    This function evaluates a tic tac toe board and returns the winner.

    Please see "assignment-4-sample-data.py" for sample data. The board will adhere
    to the same pattern. The board may by 3x3, 4x4, 5x5, or 6x6. The board will never
    have more than one winner. The board will only ever have 2 unique symbols at the same time.

    Parameters
    ----------
    board: list
        the representation of the tic-tac-toe board as a square list of lists

    Returns
    -------
    str
        the symbol of the winner or "NO WINNER" if there is no winner
    '''
    # Replace `pass` with your code. 
    # Stay within the function. Only use the parameters as input. The function should return your answer.
    board_size = len(board) # dimensions of the board: board_size x board_size
    row_X = [board[i].count("X")==board_size for i in range(board_size)]
    row_O = [board[i].count("O")==board_size for i in range(board_size)]
    columns = [x for x in zip(*board)]
    column_X = [columns[i].count("X")==board_size for i in range(board_size)] 
    column_O = [columns[i].count("O")==board_size for i in range(board_size)]
    diagonal_updown = [board[i][i] for i in range(board_size)]
    diagonal_ud_X = bool(diagonal_updown.count("X")==board_size)
    diagonal_ud_O = bool(diagonal_updown.count("O")==board_size)
    diagonal_downup = [board[i][board_size-1-i] for i in range(board_size)]
    diagonal_du_X = bool(diagonal_downup.count("X")==board_size)
    diagonal_du_O = bool(diagonal_downup.count("O")==board_size)
    all_bool_X = row_X+column_X
    all_bool_O = row_O+column_O
    all_bool_X.append(diagonal_ud_X)
    all_bool_O.append(diagonal_ud_O)
    all_bool_X.append(diagonal_du_X)
    all_bool_O.append(diagonal_du_O)
    if bool(sum(all_bool_X)) == bool(sum(all_bool_O)):
      return "NO WINNER"
    elif bool(sum(all_bool_X)):
      return "X"
    elif bool(sum(all_bool_O)):
      return "O"

def eta(first_stop, second_stop, route_map):
    '''ETA. 
    25 points.

    A shuttle van service is tasked to travel along a predefined circlar route.
    This route is divided into several legs between stops.
    The route is one-way only, and it is fully connected to itself.

    This function returns how long it will take the shuttle to arrive at a stop
    after leaving another stop.

    Please see "mod-4-ipa-1-sample-data.py" for sample data. The route map will
    adhere to the same pattern. The route map may contain more legs and more stops,
    but it will always be one-way and fully enclosed.

    Parameters
    ----------
    first_stop: str
        the stop that the shuttle will leave
    second_stop: str
        the stop that the shuttle will arrive at
    route_map: dict
        the data describing the routes

    Returns
    -------
    int
        the time it will take the shuttle to travel from first_stop to second_stop
    '''
    # Replace `pass` with your code. 
    # Stay within the function. Only use the parameters as input. The function should return your answer.
    total_travel = 0
    key_list = list(route_map.keys())
    i = 0
    for i in range(len(key_list)):
      if first_stop == key_list[i][0]:
        total_travel += route_map[key_list[i]]["travel_time_mins"]
        break
    def continuation(second_stop, key_list):
      route = route_map
      travel_time = 0
      j = i
      j += 1
      while j < len(key_list):
        travel_time += route[key_list[j]]["travel_time_mins"]
        if second_stop != key_list[j][1]:
          j += 1
        else:
          break
      if j == len(key_list):
        j = 0
        # cannot do recursion due to the nature of the continuation function (e.g. j is set to value i before the conditions, etc.)
        while j < len(key_list):
          travel_time += route[key_list[j]]["travel_time_mins"]
          if second_stop != key_list[j][1]:
            j += 1
          else:
            break
      return travel_time
    total_travel += continuation(second_stop, key_list)
    return total_travel


legs = {
     ("upd","ust"):{
         "travel_time_mins":10
     },
     ("ust","dlsu"):{
         "travel_time_mins":35
     },
     ("dlsu","admu"):{
         "travel_time_mins":55
     },
     ("admu","upd"):{
         "travel_time_mins":30
     }
}
eta('dlsu', 'ust', legs)

